version: "3.9"

services:
  frontend:
    image: mohamedhafid825/clothews-frontend:latest  # ⬅️ Replace with your Docker Hub image
    container_name: frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    image: mohamedhafid825/clothews-backend:latest   # ⬅️ Replace with your Docker Hub image
    container_name: backend
    env_file: ./backend/.env
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
